version: '3'
services:

  end:
    image: enderwar/togupsy:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5076
    ports:
      - 5076:5076  
  Sasha:
    image: alexawler/psychotest:latest
    ports:
      - 4200:80 



  